version: 2.1

jobs:
  build:
    docker:
      - image: cypress/base:14.17.0
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: cd ./astra/web && npm install
      - run:
          name: Debug Current Directory
          command: cd ./astra/web && pwd
      - run:
          name: Run Playwright tests
          command: cd ./astra/web && npm run test
