version: 2.1

jobs:
  build:
    docker:
      - image: cypress/base:14.17.0
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Navigate to astra/web folder
          command: cd ./astra/web
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run Playwright tests
          command: npx playwright test
      - run:
          name: Debug Current Directory
          command: pwd
